In [1]:
import numpy as np

# Array creation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(1, 13)
arr3 = np.random.randint(1, 100, size=(3, 4))

print("1D Array:", arr1)
print("2D Random Array:\n", arr3)

# Indexing & slicing
print("First element:", arr1[0])
print("Slice:", arr1[1:4])
print("2D Slice:\n", arr3[:, 1:3])

# Mathematical operations
print("Sum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Max:", np.max(arr1))

# Axis-wise operations
print("Column-wise sum:", np.sum(arr3, axis=0))
print("Row-wise mean:", np.mean(arr3, axis=1))

# Reshaping
reshaped = arr2.reshape(3, 4)
print("Reshaped Array:\n", reshaped)

# Broadcasting
broadcasted = reshaped + 10
print("Broadcasted Array:\n", broadcasted)

# Save and load
np.save("sample_array.npy", reshaped)
loaded_array = np.load("sample_array.npy")
print("Loaded Array:\n", loaded_array)


1D Array: [1 2 3 4 5]
2D Random Array:
 [[68 50 97 21]
 [84 21  1 98]
 [62 77 37 73]]
First element: 1
Slice: [2 3 4]
2D Slice:
 [[50 97]
 [21  1]
 [77 37]]
Sum: 15
Mean: 3.0
Max: 5
Column-wise sum: [214 148 135 192]
Row-wise mean: [59.   51.   62.25]
Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Broadcasted Array:
 [[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
Loaded Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
